version: '2.0'

services:
  web:
    build: ./
    image: muse-for-music:latest
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://muse-for-music:muse4music@db/MusicRepo?charset=utf8mb4
      - JWT_SECRET_KEY=test
      - LOG_PATH=/var/log
      - "WAIT_HOSTS=db:3306"
    networks:
      - muse-for-music
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: muse-for-music
      MYSQL_PASSWORD: muse4music
      MYSQL_DATABASE: MusicRepo
    networks:
      - muse-for-music
networks:
  muse-for-music:
    driver: bridge