"""Drop other_to_citations table

Revision ID: 08b69a172bb7
Revises: 638ae6935168
Create Date: 2019-10-20 19:50:13.613872

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08b69a172bb7"
down_revision = "638ae6935168"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("other_to_citations")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "other_to_citations",
        dbColumn("id", dbINTEGER(), nullable=False),
        dbColumn("citations_id", dbINTEGER(), nullable=True),
        dbColumn("citation", dbTEXT(), nullable=True),
        dbForeignKeyConstraint(
            ["citations_id"], ["citations.id"], name="other_to_citations_ibfk_1"
        ),
        dbPrimaryKeyConstraint("id", name="pk_other_to_citations"),
    )
    # ### end Alembic commands ###
