"""Add repetition counts to composition and more taxonomy entries to opus

Revision ID: 38ed909ec074
Revises: 6332c52bf469
Create Date: 2018-05-23 15:45:46.307717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ed909ec074'
down_revision = '6332c52bf469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition') as batch_op:
        batch_op.add_column(sa.Column('nr_repetitions_1_2', sa.Integer(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('nr_repetitions_3_4', sa.Integer(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('nr_repetitions_5_6', sa.Integer(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('nr_repetitions_7_10', sa.Integer(), server_default=sa.text("'0'"), nullable=True))
        batch_op.drop_column('nr_varied_repetitions')
        batch_op.drop_column('nr_exact_repetitions')

    with op.batch_alter_table('opus') as batch_op:
        batch_op.drop_constraint('opus_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('opus_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('opus_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_opus_tonalitaet_id_tonalitaet'), 'tonalitaet', ['tonalitaet_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_opus_grundton_id_grundton'), 'grundton', ['grundton_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_opus_genre_id_gattung_nineteenth_century'), 'gattung_nineteenth_century', ['genre_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('tempo') as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tempo_parent_id_tempo'), 'tempo', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempo') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tempo_parent_id_tempo'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('opus') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_opus_genre_id_gattung_nineteenth_century'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_opus_grundton_id_grundton'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_opus_tonalitaet_id_tonalitaet'), type_='foreignkey')
        batch_op.create_foreign_key('opus_ibfk_2', 'gattung_nineteenth_century', ['genre_id'], ['id'])
        batch_op.create_foreign_key('opus_ibfk_3', 'grundton', ['grundton_id'], ['id'])
        batch_op.create_foreign_key('opus_ibfk_4', 'tonalitaet', ['tonalitaet_id'], ['id'])

    with op.batch_alter_table('composition') as batch_op:
        batch_op.add_column(sa.Column('nr_exact_repetitions', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('nr_varied_repetitions', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
        batch_op.drop_column('nr_repetitions_7_10')
        batch_op.drop_column('nr_repetitions_5_6')
        batch_op.drop_column('nr_repetitions_3_4')
        batch_op.drop_column('nr_repetitions_1_2')

    # ### end Alembic commands ###
