"""empty message

Revision ID: 494a304bb471
Revises: 08b69a172bb7
Create Date: 2021-03-28 22:15:00.829766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494a304bb471'
down_revision = '08b69a172bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opus', schema=None) as batch_op:
        batch_op.drop_index('ix_opus_original_name')
        batch_op.create_index(batch_op.f('ix_opus_original_name'), ['original_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opus_original_name'))
        batch_op.create_index('ix_opus_original_name', ['original_name'], unique=1)

    # ### end Alembic commands ###
