"""Drop tempo context

Revision ID: 563a2aa9584c
Revises: 88a8835f8310
Create Date: 2018-08-21 17:08:34.527113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563a2aa9584c'
down_revision = '88a8835f8310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempo_group', schema=None) as batch_op:
        batch_op.drop_constraint('tempo_group_ibfk_1', type_='foreignkey')
        batch_op.drop_column('tempo_context_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempo_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_context_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('tempo_group_ibfk_1', 'tempo_context', ['tempo_context_id'], ['id'])

    # ### end Alembic commands ###
