"""empty message

Revision ID: 6332c52bf469
Revises: 5d1b25e05af8
Create Date: 2018-05-15 14:32:56.038787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6332c52bf469'
down_revision = '5d1b25e05af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('type', sa.Enum('person', 'opus', 'part', 'subpart', 'voice', name='typeenum'), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup'))
    )
    op.drop_constraint(None, 'opus', type_='foreignkey')
    op.drop_constraint(None, 'opus', type_='foreignkey')
    op.drop_constraint(None, 'opus', type_='foreignkey')
    op.create_foreign_key(op.f('fk_opus_tonalitaet_id_tonalitaet'), 'opus', 'tonalitaet', ['tonalitaet_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_opus_grundton_id_grundton'), 'opus', 'grundton', ['grundton_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_opus_genre_id_gattung_nineteenth_century'), 'opus', 'gattung_nineteenth_century', ['genre_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_opus_genre_id_gattung_nineteenth_century'), 'opus', type_='foreignkey')
    op.drop_constraint(op.f('fk_opus_grundton_id_grundton'), 'opus', type_='foreignkey')
    op.drop_constraint(op.f('fk_opus_tonalitaet_id_tonalitaet'), 'opus', type_='foreignkey')
    op.create_foreign_key(None, 'opus', 'gattung_nineteenth_century', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'opus', 'grundton', ['grundton_id'], ['id'])
    op.create_foreign_key(None, 'opus', 'tonalitaet', ['tonalitaet_id'], ['id'])
    op.drop_table('backup')
    # ### end Alembic commands ###
