"""empty message

Revision ID: 6332c52bf469
Revises: 5d1b25e05af8
Create Date: 2018-05-15 14:32:56.038787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6332c52bf469'
down_revision = '5d1b25e05af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('type', sa.Enum('person', 'opus', 'part', 'subpart', 'voice', name='typeenum'), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup')
    # ### end Alembic commands ###
