"""empty message

Revision ID: 88a8835f8310
Revises: bb0693433148
Create Date: 2018-08-06 17:00:47.577428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a8835f8310'
down_revision = 'bb0693433148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formale_funktion_to_form',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('formale_funktion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], name=op.f('fk_formale_funktion_to_form_form_id_form')),
    sa.ForeignKeyConstraint(['formale_funktion_id'], ['formale_funktion.id'], name=op.f('fk_formale_funktion_to_form_formale_funktion_id_formale_funktion')),
    sa.PrimaryKeyConstraint('form_id', 'formale_funktion_id', name=op.f('pk_formale_funktion_to_form'))
    )
    op.execute('INSERT INTO `formale_funktion_to_form` (`form_id`, `Formale_funktion_id`) SELECT `form`.`id`, `form`.`formal_function_id` FROM `form`')
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_constraint('form_ibfk_2', type_='foreignkey')
        batch_op.drop_column('formal_function_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formal_function_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('form_ibfk_2', 'formale_funktion', ['formal_function_id'], ['id'])
    op.execute('UPDATE `form` SET `formal_function_id` = (SELECT `formale_funktion_to_form`.`formale_funktion_id` FROM `formale_funktion_to_form` WHERE `formale_funktion_to_form`.`form_id` = `form`.`id`)')
    op.drop_table('formale_funktion_to_form')
    # ### end Alembic commands ###
