"""taxonomies_mappings

Revision ID: 8df3ac819840
Revises: b37780ea002a
Create Date: 2026-05-19 14:46:08.620632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8df3ac819840"
down_revision = "b37780ea002a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("akkord", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("ambitus_einbettung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("ambitus_entwicklung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("anteil", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("anzahl_melodietoene", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("artikulation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("auftreten_satz", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("auftreten_werkausschnitt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("ausdruck", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("bewegung_im_tonraum", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("dissonanzen", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("dissonanzgrad", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("epoche", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("formale_funktion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("formschema", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("frequenz", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("gattung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("gattung_nineteenth_century", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("grundton", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_dichte", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_entwicklung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_funktion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "harmonische_funktion_verwandschaft", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_komplexitaet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_phaenomene", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("harmonische_stufe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("instrument", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "instrumentierung_einbettung_qualitaet", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "instrumentierung_einbettung_quantitaet", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("intervall", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("intervallik", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("lautstaerke", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("lautstaerke_einbettung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("lautstaerke_entwicklung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("lautstaerke_zusatz", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("melodiebewegung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("melodieform", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("musikalische_funktion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("musikalische_wendung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("notenwert", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("oktave", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("programmgegenstand", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("rhythmisches_phaenomen", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("rhythmustyp", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("satzart_allgemein", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("satzart_speziell", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("spezifikation_anteil", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("spezifikation_auftreten", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("spezifikation_instrument", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("spielanweisung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("taktart", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("tempo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("tempo_einbettung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("tempo_entwicklung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("tonalitaet", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("tonmalerei", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("verarbeitungstechnik", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("verzierung", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("voice_to_voice_relation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    with op.batch_alter_table("zitat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mapping", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("zitat", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("voice_to_voice_relation", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("verzierung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("verarbeitungstechnik", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("tonmalerei", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("tonalitaet", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("tempo_entwicklung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("tempo_einbettung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("tempo", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("taktart", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("spielanweisung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("spezifikation_instrument", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("spezifikation_auftreten", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("spezifikation_anteil", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("satzart_speziell", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("satzart_allgemein", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("rhythmustyp", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("rhythmisches_phaenomen", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("programmgegenstand", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("oktave", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("notenwert", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("musikalische_wendung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("musikalische_funktion", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("melodieform", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("melodiebewegung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("lautstaerke_zusatz", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("lautstaerke_entwicklung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("lautstaerke_einbettung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("lautstaerke", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("intervallik", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("intervall", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table(
        "instrumentierung_einbettung_quantitaet", schema=None
    ) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table(
        "instrumentierung_einbettung_qualitaet", schema=None
    ) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("instrument", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_stufe", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_phaenomene", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_komplexitaet", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table(
        "harmonische_funktion_verwandschaft", schema=None
    ) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_funktion", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_entwicklung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("harmonische_dichte", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("grundton", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("gattung_nineteenth_century", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("gattung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("frequenz", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("formschema", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("formale_funktion", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("epoche", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("dissonanzgrad", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("dissonanzen", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("bewegung_im_tonraum", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("ausdruck", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("auftreten_werkausschnitt", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("auftreten_satz", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("artikulation", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("anzahl_melodietoene", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("anteil", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("ambitus_entwicklung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("ambitus_einbettung", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    with op.batch_alter_table("akkord", schema=None) as batch_op:
        batch_op.drop_column("mapping")

    # ### end Alembic commands ###
