"""empty message

Revision ID: b266a684b744
Revises: 5d1b25e05af8
Create Date: 2018-05-12 20:14:53.188213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b266a684b744'
down_revision = '5d1b25e05af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akkord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['akkord.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambitus_einbettung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambitus_entwicklung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ambitus_entwicklung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anteil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anzahl_melodietoene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['artikulation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auftreten_satz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auftreten_werkausschnitt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ausdruck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('type', sa.Enum('person', 'opus', 'part', 'subpart', 'voice', name='typeenum'), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bewegung_im_tonraum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_foreign', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_exact_repetitions', sa.Integer(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('nr_varied_repetitions', sa.Integer(), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dissonanzen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dissonanzgrad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epoche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formale_funktion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['formale_funktion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formschema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequenz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gattung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gattung_nineteenth_century',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grundton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_dichte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_entwicklung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['harmonische_entwicklung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_funktion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_funktion_verwandschaft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['harmonische_funktion_verwandschaft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_komplexitaet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_phaenomene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['harmonische_phaenomene.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_stufe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['harmonische_stufe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrumentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrumentierung_einbettung_qualitaet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrumentierung_einbettung_quantitaet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervallik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['intervallik.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lautstaerke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lautstaerke_einbettung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lautstaerke_entwicklung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['lautstaerke_entwicklung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lautstaerke_zusatz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_from_page', sa.Integer(), nullable=True),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melodiebewegung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melodieform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['melodieform.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musikalische_funktion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['musikalische_funktion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musikalische_wendung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['musikalische_wendung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notenwert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oktave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_canonical_name'), 'person', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=True)
    op.create_table('programmgegenstand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['programmgegenstand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rendition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rhythm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polymetric', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rhythmisches_phaenomen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rhythmisches_phaenomen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rhythmustyp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rhythmustyp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satzart_allgemein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satzart_speziell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spielanweisung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['spielanweisung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taktart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taktart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo_einbettung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo_entwicklung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tonalitaet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tonalitaet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tonmalerei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tonmalerei.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('verarbeitungstechnik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['verarbeitungstechnik.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verzierung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['verzierung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_to_voice_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zitat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['zitat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikulation_to_rendition',
    sa.Column('rendition_id', sa.Integer(), nullable=False),
    sa.Column('artikulation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artikulation_id'], ['artikulation.id'], ),
    sa.ForeignKeyConstraint(['rendition_id'], ['rendition.id'], ),
    sa.PrimaryKeyConstraint('rendition_id', 'artikulation_id')
    )
    op.create_table('ausdruck_to_rendition',
    sa.Column('rendition_id', sa.Integer(), nullable=False),
    sa.Column('ausdruck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ausdruck_id'], ['ausdruck.id'], ),
    sa.ForeignKeyConstraint(['rendition_id'], ['rendition.id'], ),
    sa.PrimaryKeyConstraint('rendition_id', 'ausdruck_id')
    )
    op.create_table('composition_technique_to_composition',
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('verarbeitungstechnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['verarbeitungstechnik_id'], ['verarbeitungstechnik.id'], ),
    sa.PrimaryKeyConstraint('composition_id', 'verarbeitungstechnik_id')
    )
    op.create_table('dramaturgic_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambitus_context_before_id', sa.Integer(), nullable=True),
    sa.Column('ambitus_context_after_id', sa.Integer(), nullable=True),
    sa.Column('ambitus_change_before_id', sa.Integer(), nullable=True),
    sa.Column('ambitus_change_after_id', sa.Integer(), nullable=True),
    sa.Column('melodic_line_before_id', sa.Integer(), nullable=True),
    sa.Column('melodic_line_after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ambitus_change_after_id'], ['ambitus_entwicklung.id'], ),
    sa.ForeignKeyConstraint(['ambitus_change_before_id'], ['ambitus_entwicklung.id'], ),
    sa.ForeignKeyConstraint(['ambitus_context_after_id'], ['ambitus_einbettung.id'], ),
    sa.ForeignKeyConstraint(['ambitus_context_before_id'], ['ambitus_einbettung.id'], ),
    sa.ForeignKeyConstraint(['melodic_line_after_id'], ['melodiebewegung.id'], ),
    sa.ForeignKeyConstraint(['melodic_line_before_id'], ['melodiebewegung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loudness_before_id', sa.Integer(), nullable=True),
    sa.Column('loudness_after_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_trend_before_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_trend_after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dynamic_trend_after_id'], ['lautstaerke_einbettung.id'], ),
    sa.ForeignKeyConstraint(['dynamic_trend_before_id'], ['lautstaerke_einbettung.id'], ),
    sa.ForeignKeyConstraint(['loudness_after_id'], ['lautstaerke.id'], ),
    sa.ForeignKeyConstraint(['loudness_before_id'], ['lautstaerke.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_marking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamic_id', sa.Integer(), nullable=True),
    sa.Column('lautstaerke_id', sa.Integer(), nullable=True),
    sa.Column('lautstaerke_zusatz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamic.id'], ),
    sa.ForeignKeyConstraint(['lautstaerke_id'], ['lautstaerke.id'], ),
    sa.ForeignKeyConstraint(['lautstaerke_zusatz_id'], ['lautstaerke_zusatz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epoche_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('epoche_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['epoche_id'], ['epoche.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'epoche_id')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_schema_id', sa.Integer(), nullable=True),
    sa.Column('formal_function_id', sa.Integer(), nullable=True),
    sa.Column('contains_theme', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_schema_id'], ['formschema.id'], ),
    sa.ForeignKeyConstraint(['formal_function_id'], ['formale_funktion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gattung_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('gattung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['gattung_id'], ['gattung.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'gattung_id')
    )
    op.create_table('harmonics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harmonic_function_modulation_id', sa.Integer(), nullable=True),
    sa.Column('degree_of_dissonance_id', sa.Integer(), nullable=True),
    sa.Column('nr_of_different_chords_per_measure', sa.Float(), nullable=True),
    sa.Column('harmonic_density_id', sa.Integer(), nullable=True),
    sa.Column('harmonic_complexity_id', sa.Integer(), nullable=True),
    sa.Column('nr_of_melody_tones_per_harmony', sa.Float(), nullable=True),
    sa.Column('melody_tones_in_melody_one_id', sa.Integer(), nullable=True),
    sa.Column('melody_tones_in_melody_two_id', sa.Integer(), nullable=True),
    sa.Column('harmonic_rhythm_is_static', sa.Boolean(), nullable=True),
    sa.Column('harmonic_rhythm_follows_rule', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['degree_of_dissonance_id'], ['dissonanzgrad.id'], ),
    sa.ForeignKeyConstraint(['harmonic_complexity_id'], ['harmonische_komplexitaet.id'], ),
    sa.ForeignKeyConstraint(['harmonic_density_id'], ['harmonische_dichte.id'], ),
    sa.ForeignKeyConstraint(['harmonic_function_modulation_id'], ['harmonische_funktion_verwandschaft.id'], ),
    sa.ForeignKeyConstraint(['melody_tones_in_melody_one_id'], ['anzahl_melodietoene.id'], ),
    sa.ForeignKeyConstraint(['melody_tones_in_melody_two_id'], ['anzahl_melodietoene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('create', 'update', 'delete', name='methodenum'), nullable=True),
    sa.Column('type', sa.Enum('person', 'opus', 'part', 'subpart', 'voice', name='typeenum'), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'instrument_id')
    )
    op.create_table('instrumentation_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instr_quantity_before_id', sa.Integer(), nullable=True),
    sa.Column('instr_quantity_after_id', sa.Integer(), nullable=True),
    sa.Column('instr_quality_before_id', sa.Integer(), nullable=True),
    sa.Column('instr_quality_after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instr_quality_after_id'], ['instrumentierung_einbettung_qualitaet.id'], ),
    sa.ForeignKeyConstraint(['instr_quality_before_id'], ['instrumentierung_einbettung_qualitaet.id'], ),
    sa.ForeignKeyConstraint(['instr_quantity_after_id'], ['instrumentierung_einbettung_quantitaet.id'], ),
    sa.ForeignKeyConstraint(['instr_quantity_before_id'], ['instrumentierung_einbettung_quantitaet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instumentation_to_instrument',
    sa.Column('instrumentation_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['instrumentation_id'], ['instrumentation.id'], ),
    sa.PrimaryKeyConstraint('instrumentation_id', 'instrument_id')
    )
    op.create_table('lautstaerke_entwicklung_to_dynamic',
    sa.Column('dynamic_id', sa.Integer(), nullable=False),
    sa.Column('lautstaerke_entwicklung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamic.id'], ),
    sa.ForeignKeyConstraint(['lautstaerke_entwicklung_id'], ['lautstaerke_entwicklung.id'], ),
    sa.PrimaryKeyConstraint('dynamic_id', 'lautstaerke_entwicklung_id')
    )
    op.create_table('opus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('score_link', sa.Text(), nullable=True),
    sa.Column('first_printed_at', sa.String(length=255), nullable=True),
    sa.Column('first_printed_in', sa.Integer(), nullable=True),
    sa.Column('composition_year', sa.Integer(), nullable=True),
    sa.Column('composition_place', sa.String(length=255), nullable=True),
    sa.Column('first_played_at', sa.String(length=255), nullable=True),
    sa.Column('first_played_in', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('movements', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('grundton_id', sa.Integer(), nullable=True),
    sa.Column('tonalitaet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['gattung_nineteenth_century.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grundton_id'], ['grundton.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tonalitaet_id'], ['tonalitaet.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opus_name'), 'opus', ['name'], unique=True)
    op.create_index(op.f('ix_opus_original_name'), 'opus', ['original_name'], unique=True)
    op.create_table('other_to_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citations_id', sa.Integer(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'person_id')
    )
    op.create_table('programmgegenstand_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('programmgegenstand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['programmgegenstand_id'], ['programmgegenstand.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'programmgegenstand_id')
    )
    op.create_table('rhythmisches_phaenomen_to_rhythm',
    sa.Column('rhythm_id', sa.Integer(), nullable=False),
    sa.Column('rhythmisches_phaenomen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rhythm_id'], ['rhythm.id'], ),
    sa.ForeignKeyConstraint(['rhythmisches_phaenomen_id'], ['rhythmisches_phaenomen.id'], ),
    sa.PrimaryKeyConstraint('rhythm_id', 'rhythmisches_phaenomen_id')
    )
    op.create_table('rhythmustyp_to_rhythm',
    sa.Column('rhythm_id', sa.Integer(), nullable=False),
    sa.Column('rhythmustyp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rhythm_id'], ['rhythm.id'], ),
    sa.ForeignKeyConstraint(['rhythmustyp_id'], ['rhythmustyp.id'], ),
    sa.PrimaryKeyConstraint('rhythm_id', 'rhythmustyp_id')
    )
    op.create_table('satz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satzart_allgemein_id', sa.Integer(), nullable=True),
    sa.Column('satzart_speziell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['satzart_allgemein_id'], ['satzart_allgemein.id'], ),
    sa.ForeignKeyConstraint(['satzart_speziell_id'], ['satzart_speziell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('tonal_corrected', sa.Boolean(), nullable=True),
    sa.Column('starting_interval_id', sa.Integer(), nullable=True),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('beats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['bewegung_im_tonraum.id'], ),
    sa.ForeignKeyConstraint(['starting_interval_id'], ['intervall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spielanweisung_to_rendition',
    sa.Column('rendition_id', sa.Integer(), nullable=False),
    sa.Column('spielanweisung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rendition_id'], ['rendition.id'], ),
    sa.ForeignKeyConstraint(['spielanweisung_id'], ['spielanweisung.id'], ),
    sa.PrimaryKeyConstraint('rendition_id', 'spielanweisung_id')
    )
    op.create_table('taktart_to_rhythm',
    sa.Column('rhythm_id', sa.Integer(), nullable=False),
    sa.Column('taktart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rhythm_id'], ['rhythm.id'], ),
    sa.ForeignKeyConstraint(['taktart_id'], ['taktart.id'], ),
    sa.PrimaryKeyConstraint('rhythm_id', 'taktart_id')
    )
    op.create_table('tempo_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tempo_context_before_id', sa.Integer(), nullable=True),
    sa.Column('tempo_context_after_id', sa.Integer(), nullable=True),
    sa.Column('tempo_trend_before_id', sa.Integer(), nullable=True),
    sa.Column('tempo_trend_after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tempo_context_after_id'], ['tempo_einbettung.id'], ),
    sa.ForeignKeyConstraint(['tempo_context_before_id'], ['tempo_einbettung.id'], ),
    sa.ForeignKeyConstraint(['tempo_trend_after_id'], ['tempo_entwicklung.id'], ),
    sa.ForeignKeyConstraint(['tempo_trend_before_id'], ['tempo_entwicklung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tonmalerei_to_citations',
    sa.Column('citations_id', sa.Integer(), nullable=False),
    sa.Column('tonmalerei_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['tonmalerei_id'], ['tonmalerei.id'], ),
    sa.PrimaryKeyConstraint('citations_id', 'tonmalerei_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'taxonomy_editor', name='roleenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('akkord_to_harmonics',
    sa.Column('harmonics_id', sa.Integer(), nullable=False),
    sa.Column('akkord_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['akkord_id'], ['akkord.id'], ),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.PrimaryKeyConstraint('harmonics_id', 'akkord_id')
    )
    op.create_table('dissonanzen_to_harmonics',
    sa.Column('harmonics_id', sa.Integer(), nullable=False),
    sa.Column('dissonanzen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dissonanzen_id'], ['dissonanzen.id'], ),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.PrimaryKeyConstraint('harmonics_id', 'dissonanzen_id')
    )
    op.create_table('harmonic_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harmonics_id', sa.Integer(), nullable=True),
    sa.Column('grundton_id', sa.Integer(), nullable=True),
    sa.Column('tonalitaet_id', sa.Integer(), nullable=True),
    sa.Column('harmonische_funktion_id', sa.Integer(), nullable=True),
    sa.Column('harmonische_stufe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grundton_id'], ['grundton.id'], ),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.ForeignKeyConstraint(['harmonische_funktion_id'], ['harmonische_funktion.id'], ),
    sa.ForeignKeyConstraint(['harmonische_stufe_id'], ['harmonische_stufe.id'], ),
    sa.ForeignKeyConstraint(['tonalitaet_id'], ['tonalitaet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harmonische_entwicklung_to_harmonics',
    sa.Column('harmonics_id', sa.Integer(), nullable=False),
    sa.Column('harmonische_entwicklung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.ForeignKeyConstraint(['harmonische_entwicklung_id'], ['harmonische_entwicklung.id'], ),
    sa.PrimaryKeyConstraint('harmonics_id', 'harmonische_entwicklung_id')
    )
    op.create_table('harmonische_phaenomene_to_harmonics',
    sa.Column('harmonics_id', sa.Integer(), nullable=False),
    sa.Column('harmonische_phaenomene_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.ForeignKeyConstraint(['harmonische_phaenomene_id'], ['harmonische_phaenomene.id'], ),
    sa.PrimaryKeyConstraint('harmonics_id', 'harmonische_phaenomene_id')
    )
    op.create_table('opus_citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citations_id', sa.Integer(), nullable=True),
    sa.Column('opus_id', sa.Integer(), nullable=True),
    sa.Column('citation_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citation_type_id'], ['zitat.id'], ),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['opus_id'], ['opus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('measure_start_id', sa.Integer(), nullable=False),
    sa.Column('measure_end_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('occurence_in_movement_id', sa.Integer(), nullable=True),
    sa.Column('instrumentation_context_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_context_id', sa.Integer(), nullable=True),
    sa.Column('tempo_context_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('dramaturgic_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dramaturgic_context_id'], ['dramaturgic_context.id'], ),
    sa.ForeignKeyConstraint(['dynamic_context_id'], ['dynamic_context.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['instrumentation_context_id'], ['instrumentation_context.id'], ),
    sa.ForeignKeyConstraint(['measure_end_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['measure_start_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['occurence_in_movement_id'], ['auftreten_satz.id'], ),
    sa.ForeignKeyConstraint(['opus_id'], ['opus.id'], ),
    sa.ForeignKeyConstraint(['tempo_context_id'], ['tempo_context.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tempo_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tempo_context_id'], ['tempo_context.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=5), nullable=False),
    sa.Column('occurence_in_part_id', sa.Integer(), nullable=True),
    sa.Column('share_of_part_id', sa.Integer(), nullable=True),
    sa.Column('instrumentation_id', sa.Integer(), nullable=True),
    sa.Column('satz_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('rhythm_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_id', sa.Integer(), nullable=True),
    sa.Column('harmonics_id', sa.Integer(), nullable=True),
    sa.Column('tempo_id', sa.Integer(), nullable=True),
    sa.Column('rendition_id', sa.Integer(), nullable=True),
    sa.Column('citations_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citations_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamic.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['harmonics_id'], ['harmonics.id'], ),
    sa.ForeignKeyConstraint(['instrumentation_id'], ['instrumentation.id'], ),
    sa.ForeignKeyConstraint(['occurence_in_part_id'], ['auftreten_werkausschnitt.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['rendition_id'], ['rendition.id'], ),
    sa.ForeignKeyConstraint(['rhythm_id'], ['rhythm.id'], ),
    sa.ForeignKeyConstraint(['satz_id'], ['satz.id'], ),
    sa.ForeignKeyConstraint(['share_of_part_id'], ['anteil.id'], ),
    sa.ForeignKeyConstraint(['tempo_id'], ['tempo_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo_entwicklung_to_tempo_group',
    sa.Column('tempo_group_id', sa.Integer(), nullable=False),
    sa.Column('tempo_entwicklung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tempo_entwicklung_id'], ['tempo_entwicklung.id'], ),
    sa.ForeignKeyConstraint(['tempo_group_id'], ['tempo_group.id'], ),
    sa.PrimaryKeyConstraint('tempo_group_id', 'tempo_entwicklung_id')
    )
    op.create_table('tempo_to_tempo_group',
    sa.Column('tempo_group_id', sa.Integer(), nullable=False),
    sa.Column('tempo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tempo_group_id'], ['tempo_group.id'], ),
    sa.ForeignKeyConstraint(['tempo_id'], ['tempo.id'], ),
    sa.PrimaryKeyConstraint('tempo_group_id', 'tempo_id')
    )
    op.create_table('musikalische_wendung_to_sub_part',
    sa.Column('sub_part_id', sa.Integer(), nullable=False),
    sa.Column('musikalische_wendung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musikalische_wendung_id'], ['musikalische_wendung.id'], ),
    sa.ForeignKeyConstraint(['sub_part_id'], ['sub_part.id'], ),
    sa.PrimaryKeyConstraint('sub_part_id', 'musikalische_wendung_id')
    )
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subpart_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('instrumentation_id', sa.Integer(), nullable=False),
    sa.Column('satz_id', sa.Integer(), nullable=True),
    sa.Column('has_melody', sa.Boolean(), nullable=True),
    sa.Column('melody_form_id', sa.Integer(), nullable=True),
    sa.Column('intervallik_id', sa.Integer(), nullable=True),
    sa.Column('is_repetitive', sa.Boolean(), nullable=True),
    sa.Column('contains_repetition_from_outside', sa.Boolean(), nullable=True),
    sa.Column('cites_own_melody_later', sa.Boolean(), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), nullable=True),
    sa.Column('highest_pitch_id', sa.Integer(), nullable=True),
    sa.Column('highest_octave_id', sa.Integer(), nullable=True),
    sa.Column('lowest_pitch_id', sa.Integer(), nullable=True),
    sa.Column('lowest_octave_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('occurence_in_part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['highest_octave_id'], ['oktave.id'], ),
    sa.ForeignKeyConstraint(['highest_pitch_id'], ['grundton.id'], ),
    sa.ForeignKeyConstraint(['instrumentation_id'], ['instrumentation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervallik_id'], ['intervallik.id'], ),
    sa.ForeignKeyConstraint(['lowest_octave_id'], ['oktave.id'], ),
    sa.ForeignKeyConstraint(['lowest_pitch_id'], ['grundton.id'], ),
    sa.ForeignKeyConstraint(['melody_form_id'], ['melodieform.id'], ),
    sa.ForeignKeyConstraint(['occurence_in_part_id'], ['auftreten_werkausschnitt.id'], ),
    sa.ForeignKeyConstraint(['satz_id'], ['satz.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['anteil.id'], ),
    sa.ForeignKeyConstraint(['subpart_id'], ['sub_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musikalische_funktion_to_voice',
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('musikalische_funktion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musikalische_funktion_id'], ['musikalische_funktion.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.id'], ),
    sa.PrimaryKeyConstraint('voice_id', 'musikalische_funktion_id')
    )
    op.create_table('notenwert_to_voice',
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('notenwert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notenwert_id'], ['notenwert.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.id'], ),
    sa.PrimaryKeyConstraint('voice_id', 'notenwert_id')
    )
    op.create_table('related_voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.Integer(), nullable=True),
    sa.Column('related_voice_id', sa.Integer(), nullable=True),
    sa.Column('type_of_relationship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_voice_id'], ['voice.id'], ),
    sa.ForeignKeyConstraint(['type_of_relationship_id'], ['voice_to_voice_relation.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verzierung_to_voice',
    sa.Column('voice_id', sa.Integer(), nullable=False),
    sa.Column('verzierung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['verzierung_id'], ['verzierung.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.id'], ),
    sa.PrimaryKeyConstraint('voice_id', 'verzierung_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verzierung_to_voice')
    op.drop_table('related_voices')
    op.drop_table('notenwert_to_voice')
    op.drop_table('musikalische_funktion_to_voice')
    op.drop_table('voice')
    op.drop_table('musikalische_wendung_to_sub_part')
    op.drop_table('tempo_to_tempo_group')
    op.drop_table('tempo_entwicklung_to_tempo_group')
    op.drop_table('sub_part')
    op.drop_table('tempo_group')
    op.drop_table('part')
    op.drop_table('opus_citation')
    op.drop_table('harmonische_phaenomene_to_harmonics')
    op.drop_table('harmonische_entwicklung_to_harmonics')
    op.drop_table('harmonic_center')
    op.drop_table('dissonanzen_to_harmonics')
    op.drop_table('akkord_to_harmonics')
    op.drop_table('user_role')
    op.drop_table('tonmalerei_to_citations')
    op.drop_table('tempo_context')
    op.drop_table('taktart_to_rhythm')
    op.drop_table('spielanweisung_to_rendition')
    op.drop_table('sequence')
    op.drop_table('satz')
    op.drop_table('rhythmustyp_to_rhythm')
    op.drop_table('rhythmisches_phaenomen_to_rhythm')
    op.drop_table('programmgegenstand_to_citations')
    op.drop_table('person_to_citations')
    op.drop_table('other_to_citations')
    op.drop_index(op.f('ix_opus_original_name'), table_name='opus')
    op.drop_index(op.f('ix_opus_name'), table_name='opus')
    op.drop_table('opus')
    op.drop_table('lautstaerke_entwicklung_to_dynamic')
    op.drop_table('instumentation_to_instrument')
    op.drop_table('instrumentation_context')
    op.drop_table('instrument_to_citations')
    op.drop_table('history')
    op.drop_table('harmonics')
    op.drop_table('gattung_to_citations')
    op.drop_table('form')
    op.drop_table('epoche_to_citations')
    op.drop_table('dynamic_marking')
    op.drop_table('dynamic_context')
    op.drop_table('dramaturgic_context')
    op.drop_table('composition_technique_to_composition')
    op.drop_table('ausdruck_to_rendition')
    op.drop_table('artikulation_to_rendition')
    op.drop_table('zitat')
    op.drop_table('voice_to_voice_relation')
    op.drop_table('verzierung')
    op.drop_table('verarbeitungstechnik')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('tonmalerei')
    op.drop_table('tonalitaet')
    op.drop_table('tempo_entwicklung')
    op.drop_table('tempo_einbettung')
    op.drop_table('tempo')
    op.drop_table('taktart')
    op.drop_table('spielanweisung')
    op.drop_table('satzart_speziell')
    op.drop_table('satzart_allgemein')
    op.drop_table('rhythmustyp')
    op.drop_table('rhythmisches_phaenomen')
    op.drop_table('rhythm')
    op.drop_table('rendition')
    op.drop_table('programmgegenstand')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_index(op.f('ix_person_canonical_name'), table_name='person')
    op.drop_table('person')
    op.drop_table('oktave')
    op.drop_table('notenwert')
    op.drop_table('musikalische_wendung')
    op.drop_table('musikalische_funktion')
    op.drop_table('melodieform')
    op.drop_table('melodiebewegung')
    op.drop_table('measure')
    op.drop_table('lautstaerke_zusatz')
    op.drop_table('lautstaerke_entwicklung')
    op.drop_table('lautstaerke_einbettung')
    op.drop_table('lautstaerke')
    op.drop_table('intervallik')
    op.drop_table('intervall')
    op.drop_table('instrumentierung_einbettung_quantitaet')
    op.drop_table('instrumentierung_einbettung_qualitaet')
    op.drop_table('instrumentation')
    op.drop_table('instrument')
    op.drop_table('harmonische_stufe')
    op.drop_table('harmonische_phaenomene')
    op.drop_table('harmonische_komplexitaet')
    op.drop_table('harmonische_funktion_verwandschaft')
    op.drop_table('harmonische_funktion')
    op.drop_table('harmonische_entwicklung')
    op.drop_table('harmonische_dichte')
    op.drop_table('grundton')
    op.drop_table('gattung_nineteenth_century')
    op.drop_table('gattung')
    op.drop_table('frequenz')
    op.drop_table('formschema')
    op.drop_table('formale_funktion')
    op.drop_table('epoche')
    op.drop_table('dynamic')
    op.drop_table('dissonanzgrad')
    op.drop_table('dissonanzen')
    op.drop_table('composition')
    op.drop_table('citations')
    op.drop_table('bewegung_im_tonraum')
    op.drop_table('backup')
    op.drop_table('ausdruck')
    op.drop_table('auftreten_werkausschnitt')
    op.drop_table('auftreten_satz')
    op.drop_table('artikulation')
    op.drop_table('anzahl_melodietoene')
    op.drop_table('anteil')
    op.drop_table('ambitus_entwicklung')
    op.drop_table('ambitus_einbettung')
    op.drop_table('akkord')
    # ### end Alembic commands ###
