"""Add numeric fields and measure omissions.

Revision ID: b37780ea002a
Revises: 2bdc4cdc23a5
Create Date: 2025-03-21 15:35:22.228978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37780ea002a'
down_revision = '2bdc4cdc23a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harmonics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeric_degree_of_dissonance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('numeric_harmonic_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('numeric_harmonic_complexity', sa.Float(), nullable=True))

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('omissions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_column('omissions')

    with op.batch_alter_table('harmonics', schema=None) as batch_op:
        batch_op.drop_column('numeric_harmonic_complexity')
        batch_op.drop_column('numeric_harmonic_density')
        batch_op.drop_column('numeric_degree_of_dissonance')
    # ### end Alembic commands ###
