"""empty message

Revision ID: bb0693433148
Revises: 38ed909ec074
Create Date: 2018-07-10 14:22:49.957935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0693433148'
down_revision = '38ed909ec074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harmonics', schema=None) as batch_op:
        batch_op.drop_column('nr_of_different_chords_per_measure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harmonics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nr_of_different_chords_per_measure', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
